# -*- coding: utf-8 -*-
"""Task_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14eXkyZ5-Yl32J0WMp8s4M0d6jYiOOZQM
"""

E = {0,1,2,3,4,5,6}
N = {2,4,6,8}

#Operations
print("Union of E and N is ",E.union(N))
print("Intersection of E and N is ",E.intersection(N))
print("Difference of E and N is ",E.difference(N))
print("Symmetric difference of E and N is ",E.symmetric_difference(N))

