# -*- coding: utf-8 -*-
"""project 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14eXkyZ5-Yl32J0WMp8s4M0d6jYiOOZQM
"""

list1 = [12,-7,5,64,-14]
positive_numbers = [num for num in list1 if num >= 0]
print ("positive numbers are:",positive_numbers)

list2 = [12,14,-95,3]
positive_number = [num for num in list2 if num >= 0]
print ("positive numbers are:",positive_number)

